### ISSUE TITLE
Any way to hide the 'MUTED' text?

### ISSUE THREAD

**Issue by alphaniner** [abba23/mute-sites-by-default#13]
Edit: I actually found a way, but it turns out that the tab title isn't actually smaller with the 'MUTED' text present. It was just an optical illusion I guess. Plus the method of hiding the text replaces the favicon with of all muted tabs with the little speaker button all the time.

This is a great addon, I use a site regularly that has video ads which are muted by default, but somehow the first fraction of a second sneaks through from time to time.

Unfortunately, the MUTED text on each tab is kind of annoying because it makes the tab name smaller, and my old eyes already have enough troubles. I know the addon isn't responsible for the text and it's outside the scope of the addon to remove it. But if you happen to come across a way to remove it I'd love to know.

Thanks.

**Comment by Anonymous941** [comment]
See #1 and #11.

**Comment by alphaniner** [comment]
🤦‍♂️ 

Oy, #11 was right at the top of the list before I opened this... sorry for the noise.
