### ISSUE TITLE
Unmuting doesn't work

### ISSUE THREAD

**Issue by jcg051535** [abba23/mute-sites-by-default#2]
"mute sites by default" mutes sites, but I cannot un-mute them. (Mac OS 10.14 Firefox) Neither the speaker icon nor adding the site to the whitelist works. Sites with sound work OK if the the extension is disabled. Is there some other Firefox setting that I need to change?

**Comment by abba23** [comment]
That's strange. It should really just work without changing any settings.

* Can you give me an example of a site that doesn't work and what you added to the whitelist to unmute it?
* Does the speaker icon disappear when you click it?
* Do you have any other addons installed that could interfere with this one?
* Are you using a nightly or beta version of Firefox?

**Comment by jcg051535** [comment]
Hi Thanks for you prompt reply
The website I tried and added to whitelist is * https://www.quantamagazine.org* <https://www.quantamagazine.org*/>
The speaker icon does not disappear  
See attachments for add ons
I am using Firefox 63.0.1

John Garrison
johngar@mac.com
925-885-9801 
270 La Espiral, 
Orinda CA 94563

**Comment by abba23** [comment]
I don't think you can add email attachments to issues on Github. You'll have to paste the list of addons as text instead. You might also want to edit the comment and remove your address, phone number etc.

You have to only add the actual domain name to the whitelist, excluding the protocol part (`http://` or `https://`). So just `www.quantamagazine.org` should work here.

It should still be possible though to at least temporarily unmute websites, even if they aren't whitelisted, so I'm still not sure why you can't unmute it at all. Does it also happen on other websites or just that one?

**Comment by jcg051535** [comment]
I now find that everything is muted (example www.youtube.com <http://www.youtube.com/>) even if “mute-sites-by-default” is disabled. Evidently something else is wrong. I have attempted to add the list of add-ons below
