### ISSUE TITLE
Plugin affects windows 10 system volume levels

### ISSUE THREAD

**Issue by seigun23** [abba23/mute-sites-by-default#5]
This plugin appears to not only mute and unmute specific websites, but also to manage the volume of the other programs on Windows 10. 

When sites are unmuted and a media source played, the volume of all other programs in the OS is reduced significantly. Adjusting volumes of individual programs using vound mixer in windows 10 does not fix this: Volumes are minimally affected. Media must be stopped in order to end this effect.

When the media source is in tab stopped, the system volumes return to normal. 
When the plugin is disabled, this issue dissapears. 

Is there a way to mute and unmute tabs without affecting the volume of other programs?

**Comment by abba23** [comment]
Are you sure this isn't a Windows configuration issue? The addon doesn't (and can't) manage Windows' volume by itself. It just uses functionality provided by Firefox to mute specific tabs, so the only other possibility I can see is that it's a bug in Firefox.

**Comment by seigun23** [comment]
I'm very certain it's not a windows config issue-- I have only witnessed this with firefox and the active plugin in combination. Drivers/resetting settings/ other program settings/etc. have no effect on the outcome. Disabling the plugin is the only thing that seems to fix it. 

Unless I find something new (I'll continue testing it, as I rely on Firefox), I'm also willing to think it's a bug within the browser.   Thanks for replying.

**Comment by abba23** [comment]
Does the problem still occur when you disable the addon and mute/unmute tabs manually (*right click* -> Mute/Unmute Tab or CTRL+M)?

Edit: Could it be related to [this problem](https://support.mozilla.org/en-US/questions/1201925)? You might want to try the chosen solution suggested there.

**Comment by seigun23** [comment]
Hm, I wrote a message a few minutes ago, but it looks like it didn't post. I got a little trigger happy and didn't see your link until I thought about re-writing it. I had just found this exact same solution! 

I tried it out ( had to unset the setting it was on--- it was already on "Do Nothing" ) and put it back again.  So far so good! Thanks for the sleuthing!

**Comment by abba23** [comment]
Thanks for the update! I'll close this issue then.
