### ISSUE TITLE
Whitelist -> Blacklist

### ISSUE THREAD

**Issue by adraffy** [abba23/mute-sites-by-default#6]
Could you add an option to reverse the entire functionality?  

eg. Tabs are unmuted by default unless Blacklisted.

**Comment by abba23** [comment]
[This has been suggested before](https://github.com/abba23/mute-sites-by-default/issues/4). I still don't want to do it, mainly because it would mean I'd have to invest time in rewriting most of the addon for a feature that I personally don't need at all.
