### ISSUE TITLE
Add notification when muting/unmuting tab?

### ISSUE THREAD

**Issue by Smile4ever** [abba23/mute-sites-by-default#7]
This extension is a wonderful solution for me. Since I use Tab Center Reborn (a extension that shows the tabs in the sidebar) and I hide the mute icons by default, it's sometimes hard for me to see whether the tab is still muted or not, especially when not yet playing a sound.

It could be helpful to see a notification when a tab is muted or unmuted. Is this something you plan to add?

**Comment by abba23** [comment]
Sorry, I don't plan on adding any more features myself. The addon currently does everything I need. You're welcome to create a pull request though if you want.

Maybe an "Add to whitelist" button (as suggested [here](https://github.com/abba23/mute-sites-by-default/issues/4)) that changes its icon depending on if a site is whitelisted or not would be good way to implement it.
