### ISSUE TITLE
Wildcard '*' working before AND after url

### ISSUE THREAD

**Issue by Xbye** [abba23/mute-sites-by-default#8]
I'm having an issue with getting a bunch of websites whitelisted using wildcards.
Using the **9anime** websites as an example.
https://9anime.me/
**(WARNING: Highly recommend a good adblocker before visiting sites)**

If you go to this website, it'll give you a list of websites that work as mirrors(?) for their service.
I've always used: 
`https://www10.9anime.ru/`
Some of the websites just plain-old use `www.9anime.***` but sometimes the mirrors have mirrors which turn into numbers such as `www10.9anime.***`.

Unfortunately, I can't just wildcard like this: `*.9anime.*` which would cover all situations. It seems I can only get the wildcards to work, after the url?

**Comment by abba23** [comment]
>I can't just wildcard like this: `*.9anime.*`

I'm not sure why this doesn't work for you. I just tried it and it's working fine for me.

**Comment by Xbye** [comment]
For some reason it just started working for me. Just in time since the sites mirrored. If I run into the issue again I'll make sure to post here but I had been trying to get this to work for months.
